[build]
#Config custom 
target = ".cargo/i686-kfs.json"

#
[target.i686-kfs-elf]
linker = "rust-lld"
rustflags = ["-C", "link-arg=-Tlinker.ld"]

[unstable]
build-std = ["core", "alloc"]
json-target-spec = true
